language: java
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
          - r-packages-trusty
          #- ubuntu-toolchain-r-test
          packages:
          - r-base-core
          #- r-base-dev	
          #- gcc-4.8
          #- r-cran-rserve
        before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3  
    - os: osx
      osx_image: xcode8.3
before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -f '/usr/local/include/c++'; brew install r; fi
install: mvn install -DskipTests=true -Dgpg.skip=true
before_script:
  - export R_LIBS=$HOME/RLibrary
  - export R_LIBS_SITE=$HOME/RLibrary
  - export R_LIBS_USER=$HOME/RLibrary
script: mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
